
# If not running interactively, don't do anything
[ -z "$PS1" ] && return

: ${UNAME=$(uname)}


if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

shopt -s cdspell
shopt -s checkwinsize
shopt -s histappend
shopt -s dotglob

set -o noclobber
set -o ignoreeof
# notify of bg job completion immediately
set -o notify

if test -n "$(command -v less)" ; then
    PAGER="less -FirSwX"
    MANPAGER="less -FiRswX"
else
    PAGER=more
    MANPAGER="$PAGER"
fi
export PAGER MANPAGER

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" -a -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
#case "$TERM" in
#xterm-color)
#    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
#    ;;
#*)
#    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
#    ;;
#esac

# Comment in the above and uncomment this below for a color prompt
PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]$(__git_ps1 " (%s)")\$ '

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME}: ${PWD/$HOME/~}\007"'
    ;;
*)
    ;;
esac

EDITOR=vim

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

set meta-flag on
set input-meta on
set outout-meta on
set convert-meta off

export HISTCONTROL=ignoredups:ignorespace:ignoreboth
export HISTIGNORE="&:ls:la:pwd:fg:bg:history:exit:clear"
export HISTSIZE=4096
export HISTTIMEFORMAT="%d/%m/%Y %H:%M:%S"

export WORKON_HOME=$HOME/projects/python/environments
export PROJECT_HOME=$HOME/projects/python

if [ "$UNAME" = Darwin ]; then
    source /usr/local/bin/virtualenvwrapper.sh
    source /usr/local/git/contrib/completion/git-completion.bash
elif [ "$UNAME" = Linux ]; then
    source /etc/bash_completion.d/virtualenvwrapper
fi

if ! shopt -oq posix; then
    if [ -f /usr/share/bash-completion/bash_completion ]; then
        . /usr/share/bash-completion/bash_completion
    elif [ -f /etc/bash_completion ]; then
        . /etc/bash_completion
    fi
fi

export VIRTUALENVWRAPPER_VIRTUALENV_ARGS="--no-site-packages"

export GIT_PS1_SHOWDIRTYSTATE=true
export GIT_PS1_SHOWSTASHSTATE=true
export GIT_PS1_SHOWUNTRACKEDFILES=true
export GIT_PS1_SHOWUPSTREAM="auto"

